### ISSUE TITLE
请教ch2t_write0的问题

### ISSUE THREAD

**Issue by umaYnit** [DeathWish5/rCore_tutorial_tests#3]
在rCore-Tutorial第二章的基础上运行ch2t_write0时，0x0会直接进入LoadFault trap Exception，如下是打印结果
```shell
custom Panicked at src\trap\mod.rs:35 Unsupported trap Exception(LoadFault), stval = 0x0!
```

**Comment by DeathWish5** [comment]
对，这是正常的，所以需要对 rCore-Tutorial 进行改进，增加安全检查。rCore-Tutorial 只是样例代码，并不是最终答案。读 0x0 显然是非法的行为，你要想办法避免这个问题。

**Comment by umaYnit** [comment]
我直接通过ecall传递参数的形式调用的`syscall(SYSCALL_WRITE, [1, 0x0, 10])`，按理说直接就到了汇编代码`__alltraps`这个位置，但是这段汇编代码中没有读取这个变量的操作呀，为啥直接`call trap_handler`分发时就到了`LoadFault`呢

**Comment by umaYnit** [comment]
哦哦哦。不好意思，找到问题了，是对的。这里这个`LoadFault`是已经到了kernel的`sys_write`方法，kernel再调用sbi时抛出的。我之前一直以为是还没到`sys_write`，直接就`LoadFault`了。
