### ISSUE TITLE
待解决的几个问题

### ISSUE THREAD

**Issue by zhanghx0905** [DeathWish5/rCore_tutorial_tests#4]
- `ch6_mails2` 不能保证 father 最后一次写在 child 最后一次读之前，建议把 father 第二次等待的时间改短一点
- `ch6_mails3` 在 `mails_write` 系统调用之前就触发了非法指令异常（不知道是不是我的问题

**Comment by DeathWish5** [comment]
收到，你的分析是正确的，已经着手修复。
